settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: backend
    path: .
    commands:
      run: # 餈質
        status: true # 餈質
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
